### ISSUE TITLE
Shipment labels for multiple pieces

### ISSUE THREAD

**Issue by mvdnbrk** [mvdnbrk/dhlparcel-php-api#12]
@jacobdekeizer I have merged in your PR #10.

We should still address the issue with shipment labels for a parcel with multiple pieces.

**Comment by mvdnbrk** [comment]
We should take the following steps to tackle this issue:

- [X] Add `ShipmentPiece` resource. See #29 
- [ ] Add a `pieces` variable to the `Shipment` class which is a `Pieces` resource object.
- [ ] Update the `Pieces` class so it can accept an array of `Piece` or `ShipmentPiece` objects.
- [ ] Update the `Shipments` endpoint so it adds the `pieces` from the API response to the `pieces` of the `Shipment` resource class.

Above steps can be done without changing the current behavior.
Last we can remove the current behavior and remove `barcode` and `label_id` from the `Shipment` resource class.

**Comment by mvdnbrk** [comment]
It would also be nice to have some methods for convenience like:

```php
function barcodes(): array  
function labelIds(): array
```

Backwards compatibility:
```php
function getBarcodeAttribute(): string
function getLabalIdAttribute(): string
```

The latter would also be nice to have in case you are creating a shipment with just one piece (I am doing this most of the time). In this way you don't have to deal with array of `piece` items.

**Comment by Thorry84** [comment]
I would opt against this, it shouldn't matter in the code if you have a single piece or multiple pieces in a shipment. Having two code paths for two identical situations (from a technical point of view) introduces duplicate code and code smell.

Why would you make your code only work most of the time? Most of the time you have 1 piece, but not all of the time. Since code should work all of the time and not most of the time, it should handle a collection of pieces in a shipment. Since the collection can have 1 item in it, it works perfectly fine all of the time.

Not having to 'deal' with an array of piece items seems like an unavoidable reality and to me doesn't seem like that big of a thing to deal with.

**Comment by jacobdekeizer** [comment]
@mvdnbrk I'm not a fan of magic methods, because there is no autocompletion for magic methods in any ide. I my opinion we should not worry about backwards compatibility, until we reach version 1.0. We should introduce breaking changes if necessary to create a solid base to work with.

**Comment by jacobdekeizer** [comment]
>     * Update the `Pieces` class so it can accept an array of `Piece` or `ShipmentPiece` objects.

In my opinion it should be in seperate classes

**Comment by mvdnbrk** [comment]
The `Pieces` class is in fact a collection. It is holding an array of `Piece` items.

**Comment by mvdnbrk** [comment]
@Thorry84 I would do something like this.

```php
public function getBarcode()
{
    return $this->pieces->first()->tracker_code;
}

```

So you can simply do `$shipment->getBarcode()`
versus `$shipment->pieces->first()->tracker_code` all the time.

Most of us will create a shipment with just one piece almost anytime I guess. 

Side note: I thought creating multiple pieces would create a multi collo shipment.
That was my first thought and made perfectly sense. But this will just create two different parcel parcels with separate tracking codes.

**Comment by jacobdekeizer** [comment]
@mvdnbrk I don't think that is a good idea. You should provide only one way to retrieve the tracking codes so it doesn't lead to confusion and it is easier to maintain.

In your case it is easier to have a `getBarcode()` method, but I think there will be many people who don't know in advance how many shipments they are going to make. In my case I need to loop through the order items from a webshop and create a shipment for them.

**Comment by mvdnbrk** [comment]
@jacobdekeizer You won't create a separate parcel for each item in an order will you?

Typically an order = one parcel.

**Comment by jacobdekeizer** [comment]
@mvdnbrk An order can have multiple products which are going to be shipped as multiple pieces.

**Comment by mvdnbrk** [comment]
@jacobdekeizer Makes sense :smile:

**Comment by Thorry84** [comment]
My 2 cents: In all use cases I've seen we don't know in advance how many pieces there will be. I guess in most cases it will be 1 piece, but it could be multiple pieces. Since we don't know we should make sure the code handles multiple pieces at any time.

I agree with @jacobdekeizer a single code path is the way to go.

Breaking backwards compatibility isn't something to get hung up on. I would consider it a nice to have, only if it doesn't make the code worse in any way. People can always lock a version or make their own branch if backwards compatibility matters to them.

**Comment by tom-it** [comment]
I'd be interested in this feature as well, sometimes I need to have 2-3labels for one shipment, it would be great if I could add the quantity and the pieceNumber (or if it would be handled automatically)
